version: "3.8"
services:
  database:
    image: postgres
    restart: on-failure:10
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    restart: on-failure:10
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./db/postgres/migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POS\
          TGRES_DB}?sslmode=disable",
        "up"
      ]
  api:
    restart: on-failure:10
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
      - migrate
    ports:
      - "8080:8080"
    volumes:
      - ./db/files/uploads:/uploads
volumes:
  pgdata: null
